### ISSUE TITLE
Inquire about the theoretical basis of 'sim1-spheres.py' under the 'graphics-lab-THSS/particles' directory

### ISSUE THREAD

**Issue by Linus-Civil** [kawa-yoiko/polygon-intersection#2]
Hello, I tried to understand the ‘sim1-spheres.py' code, but it took me a lot of time to figure it out. Therefore, I'd like to ask what literature is referenced by the simulation in the 'sim1-spheres.py' file, , such as books, courses, or other public resources.

**Comment by ayuusweetfish** [comment]
Thanks for the interest! Due to multiple people looking into these projects, I have added the report documents to the repository.

In particular, please refer to [particles/report.pdf](https://github.com/ayuusweetfish/graphics-lab-THSS/blob/master/particles/report.pdf) as well as the following:
- [Real-time Collision Culling of a Million Bodies on Graphics Processing Units](http://graphics.ewha.ac.kr/gSaP/);
- [Real-Time Rigid Body Simulation on GPUs](https://developer.nvidia.com/gpugems/gpugems3/part-v-physics-simulation/chapter-29-real-time-rigid-body-simulation-gpus);
- [Improved GPU Sorting](https://developer.nvidia.com/gpugems/gpugems2/part-vi-simulation-and-numerical-algorithms/chapter-46-improved-gpu-sorting).

**Comment by Linus-Civil** [comment]
> Thanks for the interest! Due to multiple people looking into these projects, I have added the report documents to the repository.
> 
> In particular, please refer to [particles/report.pdf](https://github.com/ayuusweetfish/graphics-lab-THSS/blob/master/particles/report.pdf) as well as the following:
> 
> * [Real-time Collision Culling of a Million Bodies on Graphics Processing Units](http://graphics.ewha.ac.kr/gSaP/);
> * [Real-Time Rigid Body Simulation on GPUs](https://developer.nvidia.com/gpugems/gpugems3/part-v-physics-simulation/chapter-29-real-time-rigid-body-simulation-gpus);
> * [Improved GPU Sorting](https://developer.nvidia.com/gpugems/gpugems2/part-vi-simulation-and-numerical-algorithms/chapter-46-improved-gpu-sorting).

Thanks for sharing! The design of this project is awesome.
